CREATE TABLE IF NOT EXISTS profile (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  supabase_user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  name VARCHAR(255)NOT NULL,
  personal_number BIGINT UNIQUE,
  email VARCHAR(255) UNIQUE,
  tel VARCHAR(20),
  city VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)