GRANT USAGE ON SCHEMA api TO service_role;
GRANT CREATE ON SCHEMA api TO service_role;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA api TO service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA api TO service_role;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA api TO service_role;
