CREATE TABLE IF NOT EXISTS test (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(1024),
  company VARCHAR(255),
  test_date DATE,
  active BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
)