CREATE TABLE IF NOT EXISTS api.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  personal_number BIGINT UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE,
  tel VARCHAR(20),
  cities VARCHAR(255) [],
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE api.profiles ENABLE ROW LEVEL SECURITY;
