DROP TABLE IF EXISTS profile;

CREATE TABLE IF NOT EXISTS profile (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  personal_number BIGINT UNIQUE,
  email VARCHAR(255) UNIQUE,
  tel VARCHAR(20),
  city VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);