GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA api TO service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA api TO service_role;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA api TO service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA api 
GRANT ALL PRIVILEGES ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA api 
GRANT ALL PRIVILEGES ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA api 
GRANT ALL PRIVILEGES ON FUNCTIONS TO service_role;
